### ISSUE TITLE
how to add / handle buttons

### ISSUE THREAD

**Issue by ellismarte** [meteor-factory/react-native-tinder-swipe-cards#104]
Hey, so on Tinder they have 4+ buttons on each card that has a specific function, 2 of them being like and dislike, im trying to add that to my screen but i don't know how i'd call handleYup or handleNope ... any ideas on how I could add buttons and then when a button is clicked transition to the next card?

**Comment by ellismarte** [comment]
currently using _forceLeftSwipe and _forceRightSwipe

**Comment by kimellexi** [comment]
Did you find out?

**Comment by dengue8830** [comment]
but buttons cannot be pressed, im trying to unify the problem

#100 #95 #62

**Comment by elizathescheisse** [comment]
Why is this closed if it was never resolved? Is there a way to pass additional props (of my choosing) to my card component?
