### ISSUE TITLE
Please add collaborators

### ISSUE THREAD

**Issue by dcworldwide** [meteor-factory/react-native-tinder-swipe-cards#18]
This is a great lib, but PRs are not being merged (totally understandable, we all are busy). What are your thoughts on inviting collaborators?

**Comment by blackavec** [comment]
i'm agree with you too. but i think it's not going to happen, my suggestion is to make PR a a fork repository from this, and call this deprecated until the owner merge them.

**Comment by vitorebatista** [comment]
Some PR has conflicts that must be resolved. 😞 
Thanks @jjoe64 whom made a great job in #47
