### ISSUE TITLE
Update npm?

### ISSUE THREAD

**Issue by ghost** [meteor-factory/react-native-tinder-swipe-cards#21]
Is it possible to have npm updated with the latest code here?  I'm getting an error when trying to use with the recent version of React Native, and it seems the error has already been fixed here with #15 

For now, updating package.json to point to this repo is a workaround (http://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json) but would be nice to be able to just pull from npm.

Thanks!

**Comment by arimado** [comment]
Thanks for the workaround!

**Comment by Nyte7** [comment]
I changed my package.json to reflect version 0.0.8 but I cannot use npm install with it.

**Comment by Colmea** [comment]
+1

Please update NPM repository :)

**Comment by yogiben** [comment]
Updated!
