### ISSUE TITLE
react native 29.0 and onwards support

### ISSUE THREAD

**Issue by amitneeman** [meteor-factory/react-native-tinder-swipe-cards#28]
Looks like the swiping functionality is broken from 29.0 (at least) and onwards. 
Swiping left works fine but when you try to swipe right, the card goes up. tested on an iphone 6s emulator with react native 29.0

**Comment by JakeRuth** [comment]
It's working fine for me on RN 0.33.0

**Comment by vitorebatista** [comment]
@amitneeman  could you test with the last merged PR #47  ?

**Comment by amitneeman** [comment]
Hi ive been taking some time off the project for work, will do my best to
test it asap!
בתאריך יום ג׳, 20 בדצמ׳ 2016 ב-21:01 מאת Vitor Emanuel Batista <
notifications@github.com>:
