### ISSUE TITLE
Delay when getting Next Card

### ISSUE THREAD

**Issue by indivisable** [meteor-factory/react-native-tinder-swipe-cards#46]
Does anyone else get a small delay on input when trying to swipe fast through cards? It seems there is a delay from when old card is moved to when new one initializes the pan responder. Any ideas? I am thinking we may want to use a parallel animation sequence to assure the next card is ready to go before the old one goes out of view.  I am using the Stack PR version but does same on both: https://github.com/meteor-factory/react-native-tinder-swipe-cards/pull/25

**Comment by MadeInMoon** [comment]
+1

**Comment by indivisable** [comment]
@MadeInMoon are you using the Stack Version?

**Comment by MadeInMoon** [comment]
@indivisable no I'm on the master, and it happens even when I swipe normally, with remote images and local imges > 2mo.

Each card could have a **placeholder-loader** view until the image is loaded. It should be easy to implement.

**Comment by vitorebatista** [comment]
@indivisable  could you test with the last merged PR #47  ?
