### ISSUE TITLE
Add Yes and No button

### ISSUE THREAD

**Issue by TroySK** [meteor-factory/react-native-tinder-swipe-cards#6]
Add api to trigger yes and no options from outside the component. I'm new to react native, all ideas are welcome!

**Comment by Naoto-Ida** [comment]
I second that idea. I'm actually currently working on it, might send a PR to the mods.

**Comment by MadeInMoon** [comment]
Any advancements gentlemen?

**Comment by Naoto-Ida** [comment]
I made some modifications to the library and released it with [this app](https://itunes.apple.com/us/app/fuji-rock-festival-16-app/id1112045623) where you vote on artists with a Tinder-like interface. If you like it, I could look into doing a fork of the latest build and modifying it so it is generic.

**Comment by vitorebatista** [comment]
It'll be great a PR @Naoto-Ida :)

**Comment by Naoto-Ida** [comment]
OK, I'll try and get something out this week.

**Comment by helloncanella** [comment]
Any update?

**Comment by vitorebatista** [comment]
It's possible to use `refs` to trigger the options `yup` and `nope`. 
You can check in this repo:
https://github.com/VctrySam/Tinder/blob/master/App/components/home.js#L114

Tip: use `_forceLeftSwipe` and `_forceRightSwipe` instead of `_goToNextCard`

**Comment by Naoto-Ida** [comment]
Sorry guys, haven't had time to commit this and it was done when I just started with RN so it's very sloppy.
I had difficulty isolating the buttons from the lib as it was rendered inside of the card container...
I think @vitorebatista's approach is better.

**Comment by hstemplewski** [comment]
@vitorebatista yes you right, but what if someone wants to animate card and trigger yup/nope function ?
