### ISSUE TITLE
Swipe slowly to the right, then it occurs bug - unrecognized selector sent to instance...

### ISSUE THREAD

**Issue by oneupward** [meteor-factory/react-native-tinder-swipe-cards#81]
I used this swipe-cards plugin for my project but I can see the critical bug here.
![simulator screen shot apr 8 2017 5 04 31 pm](https://cloud.githubusercontent.com/assets/9720612/24829589/71a6bdf2-1c7d-11e7-805e-220710b3d22c.png)

When I was moving slowly to the right with the card then I can see the critical error screen is occurred.

So Is there anyone who can help me with this problem?

**Comment by pbassut** [comment]
Same issue here. Did you manage to fix it @alexprodev ?
