### ISSUE TITLE
Android: Padding around component, cards disappear

### ISSUE THREAD

**Issue by mxmtsk** [meteor-factory/react-native-tinder-swipe-cards#86]
I have a View with a padding around my Swiper Component. In Android when swipping the cards disappear as if the swiper component would have `overflow: hidden`

```Javascript
<View style={styles.swiperContainer}>
            <CardSwiper
              cards={this.state.cards}
              ref="swiper"
              renderCard={(cardData) => <VideoCard {...cardData} onClick={this.cardToggle} />}
              cardKey="id"
              renderNoMoreCards={this.noMoreCards}
              onClickHandler={() => true}
              handleYup={this.handleYup}
              handleNope={this.handleNope}
              draggable={this.state.draggable}
              stack
              stackDepth={3}
            />
          </View>
```

![androidscreen](https://cloud.githubusercontent.com/assets/4848184/25640698/da7a52c8-2f90-11e7-9fb4-c8ee081a1527.png)

**Comment by ossamaweb** [comment]
+1

**Comment by luyx2412** [comment]
+1

**Comment by asgvard** [comment]
Android doesn't have overflow: visible at all. When your card is rendered, it's wrapped into Animated component that cuts everything that overflows it.
https://facebook.github.io/react-native/docs/layout-props.html#overflow
