### ISSUE TITLE
Prevent the alert on tap

### ISSUE THREAD

**Issue by luchoster** [meteor-factory/react-native-tinder-swipe-cards#88]
Is there a way to prevent the card to display the alert, on tap?
I don't want it to do anything.

thanks

**Comment by designorant** [comment]
Assuming you're using the [Quick Start Example](https://github.com/meteor-factory/react-native-tinder-swipe-cards#quick-start) just remove your `handleMaybe` prop and its corresponding function.

**Comment by luchoster** [comment]
Thanks @designorant , but that doesn't work, since I don't have a handleMaybe prop.
I did figure it out yesterday, after I went to look at the code.
```
onClickHandler={() => {}}
```
it has a onClickHandler prop, that you can pass a function to. The default it's an alert. I think that should be fixed to be empty or at least include that prop in the docs.
